baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cosmin Cloud"
theme = "hugo-flex"

# see https://gohugo.io/content-management/syntax-highlighting/#configure-syntax-highlighter
pygmentsStyle = "monokailight"
pygmentsCodefences = "true"
